[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
common_macros = "0.1.1"
lazy_static = "1.5.0"
mime_guess = "2.0.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
upon = "0.10.0"
